fix defect: CloudFormation report InsufficientCapabilitiesException during replace EIP
InsufficientCapabilitiesException: An error occurred (InsufficientCapabilitiesException) when calling the UpdateStack operation: Requires capabilities : [CAPABILITY_NAMED_IAM]